### ISSUE TITLE
Release compatible with Nextcloud 28

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#2109]
Finally we stay at end of road to launch a new release of LibreSign.

During this time we made more than 1k of commits at the project to implement a lot of improvements. We made this by totally voluntary work without funding to maintain the project. Looking the dedicated time, was more than 1k of hours dedicated to this project during this period. But, the work never finish, we wish to create an excellent signature application and totally open source because we believe at open source community and at the cooperative work and we wish to always maintain the development of this project because we love open source.

To finish this round and launch the next release, we need:
- [ ] Run locally the application to execute smoke tests
- [x] List the macro-topics that will come at next version

Would be good put here the to-do list about next release.

A very, very big thanks for all that help the project interacting at issues, sending small code contributions and believing at this project.

ref: #1959 

And,.... go ahead! Lets't go to next version! uhuuuuu!

**Comment by vitormattos** [comment]
close:  #791

**Comment by tasagore** [comment]
Great news. I can do some test if it helps.

**Comment by vitormattos** [comment]
Thanks a lot @tasagore !
The code follow unstable. I wish to launch a nightly release as pre-release when the code is more stable. Before, I will follow coding hardy every days as is possible to see looking the commits and PR's at repos of LibreSign organization here. Today I worked coding by 12 hours.

**Comment by unnilennium** [comment]
will this also include NC27 support ?

**Comment by vitormattos** [comment]
I published now the first release candidate compatible with Nexcloud 28.

https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc1/libresign-v8.0.0-rc1.tar.gz

As a RC, could have a lot of problems, all help is welcome!

**Comment by LeftoversTodayAppAdmin** [comment]
Hey @vitormattos I just tested 7.1.1 with NC 28.0.1 and the download binaries step failed. This is a feature that I could really use right now and would love to help test your RC. How would I go about trying to install it on my NC instance?

**Comment by tasagore** [comment]
Hi @vitormattos 

Thanks for the hard work! Unfortunately I don't have good news...

Tried to install in two different instances and unable to activate an application. On of them was an upgrade from 7.1.1 and have a lot of error, the other one is a clean installation and show this errors when I try to enable the app:

Upgrading from 7.1.1:
`
[PHP] Error: Undefined array key "file_user_id" at /var/www/html/portales/test/apps/libresign/lib/Migration/Version8000Date20230420125331.php#126
	POST /test/index.php/settings/apps/enable

[index] Error: Object of class DateTime could not be converted to string in file '/var/www/html/portales/test/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php' line 1432
	POST /test/index.php/settings/apps/enable
`

Installing from scratch:

`"Exception":"Exception","Message":"Database error when running migration 8000Date20230420125331 for app libresign\nThere is no table with name \"nc_nextcloud.oc_libresign_file_user\" in the schema.","Code":0,"Trace":[{"file":"/var/www/html/portales/test/lib/private/Installer.php","line":155,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"}`

Both seems problems with create/upgrade database schema, will take a look tomorrow deeply.

NC28 is one of the worst Nextcloud release plenty of bugs in the files app so probably we will have a long way to get a NC+Libresing stable configuration.

**Comment by vitormattos** [comment]
Hi @LeftoversTodayAppAdmin , the version 7.1.1 haven't support by Nextcloud 28, I ended its development.
We are focused on version 28 which we released an RC last week https://github.com/LibreSign/libresign/releases/tag/v8.0.0-rc1

**Comment by vitormattos** [comment]
Hi @tasagore I identified your problem, I didn't made a backport of PR to stable28. I will do this and create a new RC.

**Comment by vitormattos** [comment]
Say hello to a new release candidate: https://github.com/LibreSign/libresign/releases/tag/v8.0.0-rc2

**Comment by tasagore** [comment]
Hi @vitormattos 

I've been able to install Rc2 in one one instance but still fails in the other, some problems with the database creation/upgradee.

The app seems to works but there are some problems with buttons and actions that doesn't work. I'm testing with a Mac+Safari and since NC28 has tons of bugs with scrollbars, buttons that don't work, web interface behavior...not sure if it's a Libresign problem or a NC problem. For example I can request (with some problems) a signature but when I try to sign the document I click in the "sign the document" button and nothing happens but as I said, since I've upgraded to NC28 this seems to be "normal". I only have two instances upgraded to NC28 just to test Libresing, all my other installations remains in NC27 since that version runs much fine.

Will take a look from Windows tomorrow, keep you in touch.

**Comment by vitormattos** [comment]
@tasagore could you provide more details about the problems related with database?

In your tests at browser, would be good open the developer tools and check if occur problems related to LibreSign.

**Comment by vitormattos** [comment]
https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc4/libresign-v8.0.0-rc4.tar.gz

**Comment by vitormattos** [comment]
https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc4/libresign-v8.0.0-rc7.tar.gz

**Comment by DazeEnd** [comment]
@vitormattos Should I test RC7 on Nextcloud v28.0.2 or v28.0.3? Or does it matter?

**Comment by vitormattos** [comment]
Both

**Comment by glimz** [comment]
Correct link: https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc7/libresign-v8.0.0-rc7.tar.gz

**Comment by vitormattos** [comment]
Thanks @glimz !
was a copy paste problem, sorry

**Comment by glimz** [comment]
First issue:
1. I am not able to download binaries by clicking on `Donwload Binaries` (Installed with `occ`)
2. After uploading a doc, there is no preview (404)
3. There is an `accountEmail` error when I add some users to a doc to sign (Emails are not fetched for those users I guess) first screenshot below
4. When trying to view the `pdf` file with another account before signing, I cannot scroll down.
5. After setting a password, I still get an error that is password is wrong (could not sign the doc)
6. If I change `Ways to identify a person who will sign a document` to `click to sign`, I am able to sign the doc




**Please let me know if there is something specific you want me to test**




<img width="1575" alt="Screenshot 2024-03-07 at 22 58 09" src="https://github.com/LibreSign/libresign/assets/36524318/4302be99-8916-444c-a389-9356df97a05d">
<img width="1567" alt="Screenshot 2024-03-07 at 23 08 04" src="https://github.com/LibreSign/libresign/assets/36524318/d150e64d-4422-4a98-8a3d-0c506b12a6cb">

**Comment by vitormattos** [comment]
Hi @glimz could you split your report in separated issues to be more easy to interact with each item?

**Comment by vitormattos** [comment]
Thanks! Will be good to have the issues because will be possible to me to identify the problem.

I'm also making a lot of tests and fixes but is very common to me to fix a problem without issue and only send the pull request with the fix.

Also occur scenarios that have small differences and I think that I solved a problem because a test scenario was fixed but could have a very similar scenario that have problems. This is very common to occur. Because this also is good to create issues detailing the steps to reproduce the problem because will be possible to check if my scenario is different of the scenario at issue.

**Comment by glimz** [comment]
@vitormattos Would you like me to create new issues found for V8.0.0 here or use the issue tracker which contains general bugs? I could create them here, one issue per comment, or create them in the issue tracker with V8.0.0 included in the header. I don't know which you will prefer?

**Comment by glimz** [comment]
<img width="1616" alt="Screenshot 2024-03-18 at 14 01 51" src="https://github.com/LibreSign/libresign/assets/36524318/059ccc9e-bbe6-4796-b246-f452cae06949">
<img width="1612" alt="Screenshot 2024-03-18 at 14 01 08" src="https://github.com/LibreSign/libresign/assets/36524318/6bce0044-529e-499f-8844-61869be919e7">


After uploading a PDF, I get the errors (preview does not work)

**Comment by glimz** [comment]
<img width="1376" alt="Screenshot 2024-03-18 at 22 47 24" src="https://github.com/LibreSign/libresign/assets/36524318/f8f0c709-d6f1-460e-9d45-940ccdea959a">
<img width="1528" alt="Screenshot 2024-03-18 at 22 46 51" src="https://github.com/LibreSign/libresign/assets/36524318/d1d48aeb-c9a6-420b-abe4-51effe943a5e">

Internal server error (422 error code), when trying to sign the document

**Comment by glimz** [comment]
> > @vitormattos Would you like me to create new issues found for V8.0.0 here or use the issue tracker which contains general bugs? I could create them here, one issue per comment, or create them in the issue tracker with V8.0.0 included in the header. I don't know which you will prefer?
> 
> @glimz I created this issue only to communicate that the development is going ahead even though the funding is not enough to pay even an engineer to work on the project, I have voluntarily dedicated a lot of effort to stop focusing on other activities that can give me some financial return so as not to let the LibreSign project stop as it is a project that I see which is very important to many people. And I also created more as an Epic of the release compatible with Nextcloud 28.
> 
> To report specific issues, will be good to do this in specific issues. By example, the problem that you talked about the previews. Having specific issues will be easy to don't lost nothing and isolate the talk about the issue in a specific place with the scenarios containing the steps to reproduce, details about environment,... You could get by example the newest issues created at this project and also the issue template that is displayed when you create a new issue.

Thank you for the clarification. I am also looking at creating some time to contribute with bug fixes. Since the test is done on this `specific release compatible with 28 ` and it is not yet stable enough with no tags, I thought creating the bug here would be easier to track.  From now on, I will create some each issue using the templates. Thanks for the good job you do

**Comment by vitormattos** [comment]
Now we have stable releases compatible with Nextcloud server 28 and 29!

It's the party time!

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
