### ISSUE TITLE
Binaries not downloaded by clicking the button

### ISSUE THREAD

**Issue by glimz** [LibreSign/libresign#2495]
**Describe the bug**

**To Reproduce**
- I'm an authenticated user
- Go to 'administration' librsign
- Click on '.Download Binaries'

Nothing happens

**Expected behavior**
Binaries Downloaded and marked as success

**Environment information (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - LibreSign Version: libresign-v8.0.0-rc7
 - Nextcloud Server Version [e.g. 28.0.3]

**Comment by vitormattos** [comment]
I found an scenario that maybe cover your case and fixed here:
- https://github.com/LibreSign/libresign/pull/2491

In my scenario, the `/data/appdata_<instance_id>/libresign` was inaccessible to Nextcloud. Possible cause to my scenario is:
- `/data/appdata_<instance_id>/libresign` deleted handmade

**Comment by vitormattos** [comment]
Hi @glimz  I published the RC-8, could you test with this new release?

**Comment by glimz** [comment]
> Hi @glimz I published the RC-8, could you test with this new build?

I will test tomorrow and give feedback.

**Comment by DazeEnd** [comment]
In RC8, when I click the "Download binaries", the button changes its label to "Binaries downloaded", however no binaries are actually downloaded. The button label just changes.
![image](https://github.com/LibreSign/libresign/assets/2699247/fac52940-10e0-4045-ba65-c0f25f6ffefc)

**Comment by glimz** [comment]
> In RC8, when I click the "Download binaries", the button changes its label to "Binaries downloaded", however no binaries are actually downloaded. The button label just changes. ![image](https://private-user-images.githubusercontent.com/2699247/313815341-fac52940-10e0-4045-ba65-c0f25f6ffefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTc1NDYsIm5iZiI6MTcxMDc5NzI0NiwicGF0aCI6Ii8yNjk5MjQ3LzMxMzgxNTM0MS1mYWM1Mjk0MC0xMGUwLTQwNDUtYmE2NS1jMGYyNWY2ZmZlZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMjEyNzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBmNGQxZWY5YjExZDI5MDhhMmE5ZDRjZjlmNGRiNWJkNzI0MWJiMTYyNjg4MzQ3ZjIyMzZlODI4YTE0MWEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qtLNJSg5UIyeRMCirSrnnLuOPsFgNK4XutUKdJTayGQ)

Refreshing the page goes back to `Download Binaries`. Still not working as expected

**Comment by DazeEnd** [comment]
This issue still exists in v8.0.0-rc11 running on Nextcloud 28.0.4.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by DazeEnd** [comment]
This problem still exists for me using LibreSign v8.1.3 running on Nextcloud v28.0.7. When I click the "Download Binaries" button, it displays a spinning "Loading..." button that never returns. I am, however, able to install the binaries from command line.
![Screenshot from 2024-07-09 14-08-53](https://github.com/LibreSign/libresign/assets/2699247/f1f1cdd0-1f14-4a89-9ad0-2429cbb6add6)

**Comment by vitormattos** [comment]
Could you check if you get any http error or if have any log entry created to LibreSign when you start the download proccess?

Is this occurring at cli too?

**Comment by DazeEnd** [comment]
When I click the button, nothing is printed to `nextcloud.log`, the website's `error.log`,  `/var/log/httpd/error_log`, `/var/log/php-fpm/error.log`, or to `/var/log/php-fpm/www-error.log`. As far as I can tell, there are no error messages printed anywhere.

**Comment by DazeEnd** [comment]
Answering your second question, everything seems to work fine from the command line. Here is my command line and output:
```
[ceperry@einstein public_html]$ pwd
/var/www/einsteintest.relanet.com/nextcloud28/public_html
[ceperry@einstein public_html]$ sudo -u apache php occ libresign:install --all
[sudo] password for ceperry: 
Downloading java...
 52914261/52914261 [============================] 100%
Downloading JSignPdf...
 19027694/19027694 [============================] 100%
Downloading pdftk...
 7205862/7205862 [============================] 100%
Downloading cfssl...
 12054528/12054528 [============================] 100%
Downloading cfssljson...
 7643136/7643136 [============================] 100%
To use CFSSL, set the engine to cfssl with: config:app:set libresign certificate_engine --value cfssl

```

**Comment by vitormattos** [comment]
Is the check getting trouble after executing the setup from CLI?

You also can check using the command `occ libresign:configure:check`

**Comment by vitormattos** [comment]
Now, how to reproduce the possible problem?

**Comment by vitormattos** [comment]
I made more updates that affect the setup flow.

I will close this issue as solved, if this problem persist by the same scenario, go back here, if you identify a new scenario with problem, create a new issue.

Thanks by reports.
