### ISSUE TITLE
Invalid hash of binaries files - NC AIO 10

### ISSUE THREAD

**Issue by yourITMatters** [LibreSign/libresign#4810]
This is a fairly fresh install of the nextcloud AIO  as of this week. The docker host is ubuntu 24.04.2 lts

when trying to setup libresign i get the button to download binaries, once the binaries download i have the option to validate setup, but after attempting to validate setup i am once again prompted to download binaries. 

I have tried the following

occ libresign:uninstall --all
then disabled and removed the libresign app
then rebuilt the master container with imagick ghostscript and poppler-utils
then rebooted the server
then downloaded and enable the libresign app 
then occ files:scan-app-data libresign
then occ libresign:install --all 

issue persist.  
 
**Environment information (please complete the following information):**
 - OS: Docker
 - Browser chrome
 - LibreSign Version 11.0.4
 - Nextcloud Server Version [31.0.2]
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Additional context**

![Image](https://github.com/user-attachments/assets/92991b0a-c40f-4ff5-b1bf-4b6af91b8705)

**Comment by Fuseteam** [comment]
related: #3230

**Comment by yourITMatters** [comment]
Are we sure this is related to 3230?  they are on hub 8  but the reported instance is 10.

**Comment by yourITMatters** [comment]
#3230  seems to be closed

**Comment by Fuseteam** [comment]
more that it is the same issue that seems to come back, i also have this issue and i'm on 10

**Comment by Fuseteam** [comment]
i got this myself after i ran `libresign:install --all`

![Image](https://github.com/user-attachments/assets/e87abf6f-6b93-4a86-a4fa-7e991231ea59)

**Comment by yourITMatters** [comment]
> more that it is the same issue that seems to come back, i also have this issue and i'm on NC AIO 10
> 
> have you tried just running `libresign:install --all` using occ web?

I used 
sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ libresign:install --all

when i check config this is what returns

![Image](https://github.com/user-attachments/assets/f2462b19-8055-41bf-913b-14499f57f0f0)

**Comment by Fuseteam** [comment]
i _think_ that should be fine, try `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ libresign:install --java`

**Comment by yourITMatters** [comment]
I get the same result.  OCC web is not compatible with NC 31

**Comment by Fuseteam** [comment]
> OCC web is not compatible with NC 31

if you look at the repo you'll see an PR to fix that

but that's another difference, while we are both on NC AIO 10, mine is still on NC 30 🤔  not sure to what extend that matters tho—

**Comment by cordlord** [comment]
I am also having this issue, even after the very latest update. Also running NC AIO 10 with NC 30.

**Comment by moblesmarti** [comment]
I am also having this issue with NC 31.0.3

**Comment by Fuseteam** [comment]
for subscribing to the issue you can also just click subscribe on the right, so show you have the same issue you can add a 👍 on the first post

This way we keep the relevant information easier to find for the people looking into the issue

**Comment by Computermaster20** [comment]
I have done all of this as well and its completely broken. When someone goes to sign it says there is a server error and wont let them sign.  All the same error and nothing above was able to fix it.

**Comment by vitormattos** [comment]
At the moment, we don't have any customers using LibreSign with Nextcloud AIO, so we haven't prioritized specific support for it yet.

Our focus is on delivering features and improvements based on the needs of our current users and GitHub Sponsors, whose support plays a key role in helping us grow the project.

If LibreSign is useful to you and you'd like to see expanded support for Nextcloud AIO, consider supporting us — even a small contribution makes a big difference! 💚

Thank a lot by your for your interest in LibreSign and your help at this issue!

**Comment by Computermaster20** [comment]
I actually use this for my business. Where can we contribute to have this looked at please? Thank you!

**Comment by moblesmarti** [comment]
> If LibreSign is useful to you and you'd like to see expanded support for Nextcloud AIO, consider supporting us — even a small contribution makes a big difference! 💚
> 
@vitormattos 
Hi, I don't think this issue is only from nextcloud AIO. We have the same error with nextcloud 31.0.4 and libresign 11.1.2.
Thanks!

![Image](https://github.com/user-attachments/assets/9b61a4d3-3e71-4b52-b8c9-c20ed6f003fb)
![Image](https://github.com/user-attachments/assets/c8c3d60d-6472-44ac-9c19-6b14c8a39118)

**Comment by yourITMatters** [comment]
> At the moment, we don't have any customers using LibreSign with Nextcloud AIO, so we haven't prioritized specific support for it yet.
> 
> Our focus is on delivering features and improvements based on the needs of our current users and [GitHub Sponsors](https://github.com/sponsors/LibreSign), whose support plays a key role in helping us grow the project.
> 
> If LibreSign is useful to you and you'd like to see expanded support for Nextcloud AIO, consider supporting us — even a small contribution makes a big difference! 💚
> 
> Thank a lot by your for your interest in LibreSign and your help at this issue!

I appreciate that.  is there a dollar amount that would sponsor this bug fix?

**Comment by vitormattos** [comment]
Thank you so much for your interest in supporting LibreSign — it truly means a lot to us! 💚

Even a small recurring contribution helps us cover development costs and focus on improvements like this one, including better support for Nextcloud AIO.

We’d be grateful for any support you can offer. It helps us keep making LibreSign better for everyone.

**Comment by Computermaster20** [comment]
If its a matter of money they system will not allow me to donate again until the payment clears. I will be happy to become a full time sponsor after we get this resolved. Thank you! @vitormattos

**Comment by vitormattos** [comment]
Thank you so much, @Computermaster20! 💚
I appreciate your donation a lot and your willingness to support LibreSign. That kind of commitment makes a huge difference to us.

Your support motivate new contributors, help us to improve features, and ensure LibreSign stays strong and sustainable for everyone.

This project is maintained by community sponsoring and we haven't a fixed funding from other places.

Let’s keep in touch, and thank you again for being part of this with us!

**Comment by vitormattos** [comment]
I started to make more tests to try to reproduce this because I can't reproduce this at any place. I already made a small improvement here:

- #4874

**Comment by vitormattos** [comment]
Every when we get the message `Invalid hash of binaries files.`, is generated a log with the result of hash validation:

https://github.com/LibreSign/libresign/blob/0f9f70c96744a0bcb44cf45d7f206457201f0cf7/lib/Service/Install/ConfigureCheckService.php#L326-L330

This will write into `nextcloud.log` file an entry with this message and the result.

Could you put here the entire row from `nextcloud.log` file that have this message?

**Comment by yourITMatters** [comment]
{"reqId":"6qZ4SzfGZAerhficXyRe","level":3,"time":"2025-04-23T15:59:36+00:00","remoteAddr":"REDACTED-FOR-SECURITY","user":"admin","app":"libresign","method":"GET","url":"/ocs/v2.php/apps/libresign/api/v1/admin/install-and-validate?requesttoken=hR%2ByNoniae8uxy0uOhxwZ5UU7GP3NVuODUEv7so%2BVI0%3D%3A4nPme8C7HrZ7iUZramQ4LPZh1FazAxLtbDBXvIARY7k%3D","message":"Invalid hash of binaries files","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"31.0.2.1","data":{"app":"libresign","result":"{\"FILE_MISSING\":{\"legal/java.base/ADDITIONAL_LICENSE_INFO\":{\"expected\":\"9f658dfea71bdc3cc1549edfb5ad3171dbfa0082b2d91e820c09abe0b376b6bcd8b5170442a5e25e72274e98f130176bbdecfa7997c59705782b214f02136a20\",\"current\":\"\"},\"legal/java.base/ASSEMBLY_EXCEPTION\":{\"expected\":\"5516e2e9eb3a555562f600cc3cd85ae01004962a8af8c49d2598281ce622bcbee7a4bc513b94b05e3b611bb50611360171e21bae9c1b3ed7d05a0867de7d3bb2\",\"current\":\"\"},\"legal/java.base/LICENSE\":{\"expected\":\"6732288c682a39ed9edf11a151f6f48e742696f4a762c0c7d8872b99b9f6d5ab6c305064d4910b1a254862a873129f11fd0fa56ff11bc577d29303f4fb492673\",\"current\":\"\"},\"legal/java.base/aes.md\":{\"expected\":\"4d14b5ddbb4d09797264ed29ba71fab6986b4a9e75efb9402c1476e0a9e2884813d6a922dea125643b4f74e1f3e458f4e48d6c840e0f4d16ed72ffbc4611dbb2\",\"current\":\"\"},\"legal/java.base/asm.md\":{\"expected\":\"2fcf1da50a53858e5e68db51996b59ebeb8f07b698f72b67a827d4fd302f757c5c0d0479b37128d239268b635b20177a27557c1dba920fa9f12f1bec2b7f6d40\",\"current\":\"\"},\"legal/java.base/c-libutl.md\":{\"expected\":\"ae459d8ce5581ea57e203088373c1ce86d122d0e27eb871ee1383e0e64cd8a184fa207eee0e835347316e70afa24a1c95aec30def3e09d15ee19a0b2c3ad2095\",\"current\":\"\"},\"legal/java.base/cldr.md\":{\"expected\":\"8ab32a80deb12dd1f3a54a38b3335a76feb44e20fcf5ee897d47511e0acedbbedf51a241768441c56259a54c7303ddf7b57be7693c5cddb30f90741ca3257190\",\"current\":\"\"},\"legal/java.base/icu.md\":{\"expected\":\"0b31bcbdb578ac448dd145c0160c83e24ff4f1b48cada692d213e026155f5a44fc0e7b01444c5af0649e49ffd100421a890a6ed0c60722b15c4a4938a0c99b67\",\"current\":\"\"},\"legal/java.base/public_suffix.md\":{\"expected\":\"f99698fcaf492acd8bface4ca43fdf52a8baf65947e0fb82baaf953998344a01fc5f752f2b3e78e9482e8a438f91136810b82cc60ea212346800944615ad3c95\",\"current\":\"\"},\"legal/java.base/siphash.md\":{\"expected\":\"4dc96c93e28152c6a832bf58bc912ada7d399d0e3180ae5a53a30de0332672c25a2606ea9ea5333a9b6a83f9f42428a08f761b68d41ba087d7e8eee65dab45c6\",\"current\":\"\"},\"legal/java.base/unicode.md\":{\"expected\":\"06f8cd7233ab0e6d2db403765aa543f153b611fa6d1cdc571fa98dc8ff9a908c14034e31305b14c6f80ee8de5bb5e6e49dcd18c030d5b5772dc93153ea16fc19\",\"current\":\"\"},\"legal/java.base/zlib.md\":{\"expected\":\"d5441b256ea55b68fb28a3546a8d5bd24d89a551222745933c23c02b917a3955469064eeed3ccbe2764ff158f2a472aad5b9b3f91190ffefab9f6b2682a75a4d\",\"current\":\"\"},\"legal/java.compiler/ADDITIONAL_LICENSE_INFO\":{\"expected\":\"9f658dfea71bdc3cc1549edfb5ad3171dbfa0082b2d91e820c09abe0b376b6bcd8b5170442a5e25e72274e98f130176bbdecfa7997c59705782b214f02136a20\",\"current\":\"\"},\"legal/java.compiler/ASSEMBLY_EXCEPTION\":{\"expected\":\"5516e2e9eb3a555562f600cc3cd85ae01004962a8af8c49d2598281ce622bcbee7a4bc513b94b05e3b611bb50611360171e21bae9c1b3ed7d05a0867de7d3bb2\",\"current\":\"\"},\"legal/java.compiler/LICENSE\":{\"expected\":\"6732288c682a39ed9edf11a151f6f48e742696f4a762c0c7d8872b99b9f6d5ab6c305064d4910b1a254862a873129f11fd0fa56ff11bc577d29303f4fb492673\",\"current\":\"\"},\"legal/java.datatransfer/ADDITIONAL_LICENSE_INFO\":{\"expected\":\"9f658dfea71bdc3cc1549edfb5ad3171dbfa0082b2d91e820c09abe0b376b6bcd8b5170442a5e25e72274e98f130176bbdecfa7997c59705782b214f02136a20\",\"current\":\"\"},\"legal/java.datatransfer/ASSEMBLY_EXCEPTION\":{\"expected\":\"5516e2e9eb3a555562f600cc3cd85ae01004962a8af8c49d2598281ce622bcbee7a4bc513b94b05e3b611bb50611360171e21bae9c1b3ed7d05a0867de7d3bb2\",\"current\":\"\"},\"legal/java.datatransfer/LICENSE\":{\"expected\":\"6732288c682a39ed9edf11a151f6f48e742696f4a762c0c7d8872b99b9f6d5ab6c305064d4910b1a254862a873129f11fd0fa56ff11bc577d29303f4fb492673\",\"current\":\"\"},\"legal/java.desktop/ADDITIONAL_LICENSE_INFO\":{\"expected\":\"9f658dfea71bdc3cc1549edfb5ad3171dbfa0082b2d91e820c09abe0b376b6bcd8b5170442a5e25e72274e98f130176bbdecfa7997c59705782b214f02136a20\",\"current\":\"\"},\"...\":\"Over 20 items, aborting normalization\"}}"},"id":"68090ee314375"}

**Comment by Computermaster20** [comment]
[log.txt](https://github.com/user-attachments/files/19872954/log.txt)

**Comment by Adaniieel15** [comment]
Hello, I want to join this thread because I have the same issue, and I hope to help by providing information that may help resolve it.

To begin with, my Nextcloud AIO v10.12.0 is running with Nextcloud Hub version 9 (30.0.9). I have had the LibreSign app installed and configured in version 10.7.2 for the past 6 months, and it worked fine until last week. The errors I am encountering are exactly the same as those in this thread. After running libresign:install -all, some errors are fixed, but the final error "Invalid hash of binaries files" remains.

In the log, the error "Invalid hash of binaries files" reports the following:

```
[libresign] Error: Invalid hash of binaries files
GET /ocs/v2.php/apps/libresign/api/v1/admin/install-and-validate?requesttoken=C5VjceJj%2FyHNdXFs7TwDn3%2BzDAubRWdKBXMCzC9Earw%3D%3APMwNEIlRzm2GGSQ6lVkzqCrZZHLIJjdzagU2onULCOo%3D from 181.55.22.218 by adaniieel on 23/04/2025, 3:31:09 p.m.
```

I noticed something that I don't see reported here: when performing the "Download binaries" process and then "Validate configuration," right after clicking the latter option, the following appears in the log:

```
[PHP] Error: hash_file(/mnt/ncdata/appdata_oco0bnnmfaw3/libresign/x86_64/jsignpdf/jsignpdf-2.3.0.zip): Failed to open stream: No such file or directory at /var/www/html/custom_apps/libresign/lib/Service/Install/SignSetupService.php#498
GET /ocs/v2.php/apps/libresign/api/v1/admin/install-and-validate?requesttoken=C5VjceJj%2FyHNdXFs7TwDn3%2BzDAubRWdKBXMCzC9Earw%3D%3APMwNEIlRzm2GGSQ6lVkzqCrZZHLIJjdzagU2onULCOo%3D from 181.55.22.218 by adaniieel on 23/04/2025, 3:31:07 p.m.
```

I see this is related to the error because it concerns the same jsignpdf.

I hope this helps in finding a solution.

**Comment by Adaniieel15** [comment]
Hi @vitormattos,

I hope you're doing well. I wanted to follow up on the issue I previously reported. I've tried several solutions, such as reinstalling the application, rebuilding the master container, and enabling the necessary dependencies, but the problem persists.

I understand you're busy, but I would greatly appreciate any guidance or suggestions to resolve this issue. I'm available to provide more information or perform additional tests if needed.

Thank you for your time and support.

Best regards,

**Comment by Computermaster20** [comment]
> > I have an update on this. I saw an update was pushed out and most of the issues are fixed but the error shown is still there. I have had to completely stop using Libresign as it doesn't work for my customers for weeks. This sucks to say the least. Looks like I am going to have to find a new solution if this doesn't get fixed soon. Please note it is now saying Poppler is not installed and it is.
> > 
> > error | Invalid hash of binaries files.
> > 
> > ![Image](https://github.com/user-attachments/assets/787d25fc-bcf3-4b8c-8a42-73fbb9b85a66)
> 
> 
> Get the same result. I hope this has a solution.
> 
> @Computermaster20  What other app did you look for for this?

**Opensign looks promising****

**Comment by vitormattos** [comment]
@moblesmarti If is about poppler, this isn't an error and also have a tip with instructions about how to remove this information.

If is about message of invalid hashes, we already implemented a lot of checks to identify what's happening and give best feedback to sysadmins. If your environment isn't with Nextcloud AIO, isn't related to this issue because here, is specific to Nextcloud AIO. This wasn't identified in none other environments.

**Comment by Fuseteam** [comment]
@vitormattos it is very much also related to other environments as seen in https://github.com/LibreSign/libresign/issues/3230, AIO doesn't change much more than running nextcloud in a docker enviroment perhaps with some pre setup for other services, unless it is due to the docker environment i cannot see how that would influence libresign

logs have also been provided in this issue, by people who were at the time sponsors as far as i can remember….

**Comment by vitormattos** [comment]
Hi @Fuseteam,

The issue reported in #3230 has already been resolved.

Regarding the mention of `poppler-utils`, this is not related to the current issue. It’s not a problem per se and, when it does occur, there are instructions available on how to address it.

Each environment may have its own particularities. In the case of Nextcloud AIO, it uses Alpine Linux ([Dockerfile reference](https://github.com/nextcloud/all-in-one/blob/main/Containers/nextcloud/Dockerfile#L2)]), which may differ in the installed OS binaries ([how to add packages](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-os-packages-permanently-to-the-nextcloud-container)) and available [PHP extensions](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#what-about-the-pdlib-php-extension-for-the-facerecognition-app).

Other factors, such as SELinux, may also affect the configuration check, as explained in this [comment](https://github.com/LibreSign/libresign/issues/2327#issuecomment-1974877680).

At this moment, as a time and logistic about the bills payments of our team, I can only provide direct support and deeper investigation to partners or contributors who help fund the LibreSign project.

**Comment by Fuseteam** [comment]
it is definitely not SELinux, as that can't be active in docker and it certainly is not active on my set up. 

I am still not convinced tis AIO specific, sounds more like it is docker specific at most. Given that @moblesmarti also has the issue it does not sound like it is docker specific either, unless proven otherwise

**Comment by Adaniieel15** [comment]
# 🛠️ Fix LibreSign: Invalid Hash of Binaries Files (Nextcloud AIO)

## 💬 Implementer's Note

I have tried to fix this problem and honestly I followed many steps, so I'm not sure which one actually solved it. But the one that seems to have worked is the following:

1. The log shows that there are files that shouldn't be there, which causes the binary check to fail.

This is the log:

I deleted the files listed there as unexpected, then regenerated the binaries, and everything worked fine. The team is now starting to run tests.

---

## 🧩 Context

LibreSign validates that downloaded binaries match a list of authorized hashes. If it finds additional files not listed, it will throw the “Invalid hash of binaries files” error.

A typical log entry looks like:

```json
"EXTRA_FILE": {
  "jsignpdf-2.2.2/docs/JSignPdf.pdf": { "expected": "", "current": "..." },
  "jsignpdf-2.2.2/JSignPdf.jar": { "expected": "", "current": "..." },
  "jsignpdf-2.2.2/InstallCert.jar": { "expected": "", "current": "..." }
}
```

---


### 🧾 Example Log Entry (from Nextcloud logs)

Below is an actual log entry that triggered the hash validation error:

```json
{
  "reqId": "PefZOF0T2ZtPWogTBw92",
  "level": 3,
  "time": "2025-06-19T23:17:31+00:00",
  "remoteAddr": "181.55.23.166",
  "user": "adaniieel",
  "app": "libresign",
  "method": "GET",
  "url": "/ocs/v2.php/apps/libresign/api/v1/admin/configure-check",
  "message": "Invalid hash of binaries files",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
  "version": "31.0.6.2",
  "data": {
    "app": "libresign",
    "result": {
      "EXTRA_FILE": {
        "jsignpdf-2.2.2/docs/JSignPdf.pdf": {
          "expected": "",
          "current": "fcf4cc584f7aaf039cf458bad5cf8165de586bb124088945ad0f293efca7c2803457e40ced4e20ed050d3fb98625f038e65533a8d3adb84d73a8a42f07b1a592"
        },
        "jsignpdf-2.2.2/JSignPdf.jar": {
          "expected": "",
          "current": "dbc0bb7af34cc1c034cae7f5c0e05702260a26684a56ab6254025fe7a0afbf01e68f8664d73bab4b71b97142373143d1159068181ae6e137740485c38c475572"
        },
        "jsignpdf-2.2.2/InstallCert.jar": {
          "expected": "",
          "current": "748afcd66d2cb10d996ee83df4b7354f3cde9d73e8f5388b89107bd82a046cebd7982f38745c61b8dd1a5ca2099eb0e290281ea699dd6f2ebd32bc13a2794569"
        }
      }
    }
  },
  "id": "68549cd1d9ea8"
}
```

This log clearly shows that LibreSign found unexpected files under the `jsignpdf-2.2.2` directory that were not declared with valid hash expectations. These files must be manually removed for the binary validation to succeed.


## ✅ Solution

### 1. Enter the Nextcloud container

```bash
docker exec -it nextcloud-aio-nextcloud bash
```

### 2. Delete the unexpected files

```bash
rm -f /var/www/html/data/appdata_*/libresign/jsignpdf-2.2.2/JSignPdf.jar
rm -f /var/www/html/data/appdata_*/libresign/jsignpdf-2.2.2/InstallCert.jar
rm -rf /var/www/html/data/appdata_*/libresign/jsignpdf-2.2.2/docs
```

### 3. Reinstall LibreSign binaries

```bash
cd /var/www/html
php occ libresign:install --all
```

---

## 🧪 Verification

1. Access your Nextcloud instance.
2. Go to **Settings > LibreSign > Check configuration**.
3. The error `Invalid hash of binaries files` should be gone.

I really hope it works for you!!

**Comment by vitormattos** [comment]
Hi @Adaniieel15 !
First, thanks a lot by your contribution!

> This log clearly shows that LibreSign found unexpected files under the jsignpdf-2.2.2 directory that were not declared with valid hash expectations. These files must be manually removed for the binary validation to succeed.

Is very good to see your message, this indicate that the logs is working fine and that the engine to check all dependencies is working fine too.

To prevent this again, we improved the way to open a new issue and the checklist to send the important points. Sometimes only making the steps to open a new issue would be enough to solve the issue before be opened.

And, I liked a lot your report here. If you wish, you can join at our community at Telegram too: https://t.me/LibreSign, don't worry about Portuguese, we also talk in English when is necessary.

**Comment by vitormattos** [comment]
PS: Before close this issue as resolved, I will check if have a way to store and show more clear the result of dependencies hash validation. Every time security is our target.

**Comment by Adaniieel15** [comment]
> Hi [@Adaniieel15](https://github.com/Adaniieel15) ! First, thanks a lot by your contribution!
> 
> > This log clearly shows that LibreSign found unexpected files under the jsignpdf-2.2.2 directory that were not declared with valid hash expectations. These files must be manually removed for the binary validation to succeed.
> 
> Is very good to see your message, this indicate that the logs is working fine and that the engine to check all dependencies is working fine too.
> 
> To prevent this again, we improved the way to open a new issue and the checklist to send the important points. Sometimes only making the steps to open a new issue would be enough to solve the issue before be opened.
> 
> And, I liked a lot your report here. If you wish, you can join at our community at Telegram too: https://t.me/LibreSign, don't worry about Portuguese, we also talk in English when is necessary.

@vitormattos Thank you for your response. I’ve joined the Telegram group — if I ever get the chance to participate there, I’ll be present. For now, everything seems to be working well with the solution provided. The team is extending the testing, and so far, nothing else has failed. We expect to resume using it in production by next week.

**Comment by Fuseteam** [comment]
thank you very much @Adaniieel15 turns out in our case we both jsignpdf 2.2.2 and jsignpdf 2.3.0 were installed in ` /mnt/ncdata/appdata_*/libresign/x86_64/jsignpdf/`

We ended up resolving it like this:
```
docker exec -it nextcloud-aio-nextcloud bash
rm -r /mnt/ncdata/appdata_*/libresign/x86_64/jsignpdf/
mkdir /mnt/ncdata/appdata_*/libresign/x86_64/jsignpdf/
chown www-data:www-data /mnt/ncdata/appdata_*/libresign/x86_64/jsignpdf/
```

after that we moved to occ_web and ran this command
```
libresign:install --all
```
which solved the issue:

![Image](https://github.com/user-attachments/assets/b9521871-853e-4515-91b6-0e003a9b8f68)

given how @vitormattos requested for donations not once, not twice, not thrice but 4 times in this thread alone— it feels only appropriate that they compensate _you_ for the time and effort you spend to solve this issue and sharing your findings!

Jokes aside, thanks again for looking into this

**Comment by vitormattos** [comment]
I also requested a lot of times the logs.

**Comment by yourITMatters** [comment]
> I also requested a lot of times the logs.

does this help?

[libresign] Error: Invalid hash of binaries files
	POST /apps/occweb/cmd
	from 7*.1**.2**.**7 by J***@*********r.com at Jun 25, 2025, 6:25:11 PM
{
  "reqId": "E7WZ6Un9lBGlqcbEXunA",
  "level": 3,
  "time": "2025-06-25T22:25:11+00:00",
  "remoteAddr": "7*.1**.2**.**7",
  "user": "J***@*********r.com",
  "app": "libresign",
  "method": "POST",
  "url": "/apps/occweb/cmd",
  "message": "Invalid hash of binaries files",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
  "version": "31.0.6.2",
  "data": {
    "app": "libresign",
    "result": "{\"FILE_MISSING\":{\"NOTICE\":{\"expected\":\"e0c38f15ba79febedf49941bb772b99e12d8da3748e60891f3bd02ff157691b545f9a5c910197ab08b61a93c62616d98206391b2200fa4294047f35c883ac08f\",\"current\":\"\"},\"bin/java\":{\"expected\":\"acf426d4784e7d29a95e8d428dadc14364133d41175b2f5cb80861a87b78149b72ca12061ef0164786156df562f53638896cbce098f228cc62dff40bf4f575d4\",\"current\":\"\"},\"bin/jfr\":{\"expected\":\"61b31738148f683d7879157c70153f3c710bd20bdb6b5aeb23b1c73800861bc6e7e44b191951ce70ec9b5edc60abe86a05ec4abe2d6df2af73d941fe68c3af4b\",\"current\":\"\"},\"bin/jrunscript\":{\"expected\":\"184f2cfe4cbd2dffccab5e84c79a21b4bc8a96c32a11f6d1e397d59aec1a8257c8151849b5d8e7fd029b6154c017da0d464bbe66ff8df80f928a8d153667e25b\",\"current\":\"\"},\"bin/jwebserver\":{\"expected\":\"42793670d498c658bdb3ecc23af3a620a78f42736cdced637d5cafbeae5d6e19624070733c448cc64dd63ad477689d0f3621bb573afe5b61c11d2963b5995e77\",\"current\":\"\"},\"bin/keytool\":{\"expected\":\"b599f836cb2fbd9541481ff393f2dda48802eb1f65716baa01db83942f8b1d668845092ecbbb5762b0a9fb2a4a45c8491a95aa935d06e2c3f52ae0961ff8683b\",\"current\":\"\"},\"bin/rmiregistry\":{\"expected\":\"36df18959cb4ed19590d617c0bb1e87c185d6d1c115ea42869fd4fecce0069e0d5bc70f132065c06baddeb40a20b2930160c93f6e37a33764f4a04d5e4eb0fe7\",\"current\":\"\"},\"conf/jaxp.properties\":{\"expected\":\"37163a66138973c586c4d59394a1b7f2ed82c9c76a82ed0354fc3a0c96f52abb5d7f8bb3141a747953a4984b62b7efe8f2a3c40b7339ebd81d4a59413403a3a0\",\"current\":\"\"},\"conf/logging.properties\":{\"expected\":\"e869f4a3b821a9933796dc9a56ee00483493369dfbfe07b3b1d895cb8318c6821cd44134eb37513f15b830c25861b596646824ed56672d08b678fefe6a4c7504\",\"current\":\"\"},\"conf/management/jmxremote.access\":{\"expected\":\"64d33add796d2d3df7ad37aa452ee1d106174be1ade3063d73ba416211629a9a9b05177969404fdc92fcee8458450c9de4a6195744b93131303208cb6f1416ad\",\"current\":\"\"},\"conf/management/jmxremote.password.template\":{\"expected\":\"e6794168ba80a8ff733d8c1771930ae8c8fc33030e5e9ca02700f326c88a2f68ff09bc734bfd1e492ef15705b288c7918ce1f3f7174742dee6a62dfe086abd65\",\"current\":\"\"},\"conf/management/management.properties\":{\"expected\":\"4fae4e2b5f7122cd80c03b3d04fca5c4b9586be6c712dfdb729f5e85d6e71a86addfdb975be4ee7e250e28643222687f834a6456054e38331bd978aba79dae71\",\"current\":\"\"},\"conf/net.properties\":{\"expected\":\"33e4d19e8b3f84fe855842792f6cec120ca1fe2d364b6780cb1042d01bebde4c5da6184d753c81410c0fdb9a0151ac133f5971be55f80ead7330314e4d35b3c2\",\"current\":\"\"},\"conf/sdp/sdp.conf.template\":{\"expected\":\"645e30897684300d163086eea1477e5262b1fe05adc0053b26cd07898f3de6c147285acfd0fac9007022692d93b347ac321fa054ab7464b07c32f86b8c2419b1\",\"current\":\"\"},\"conf/security/java.policy\":{\"expected\":\"d2b6ea94bc3becc531926239a77c9995c543bf48232484fa0036c4e09e42ab7ee5facc10e0eed64556950980ffc9c8e56c556f34e74985c09f2384216ca461ab\",\"current\":\"\"},\"conf/security/java.security\":{\"expected\":\"dfee42c49c8682e7a76cb8094f0785d5b681f584d75a517dc2299e6c8a423dd39bd9e3d879b6ff8e2973efb397f13488e737d8565ab15d4dcc90faf752f3ca13\",\"current\":\"\"},\"conf/security/policy/README.txt\":{\"expected\":\"68a031264cf9442526307364ca74b336af55564c233c2f514cac48e910022767562f8ff6a64bb9cfcbf0fb5e755289273382c9246418a4b9207fc7761d03c64e\",\"current\":\"\"},\"conf/security/policy/limited/default_US_export.policy\":{\"expected\":\"4cfca5b10cd7addcff887c8f3621d2fbec1b5632436326377b0ce5af1ae3e8b68ac5a743ca6082fc79991b8eec703a6e1dfd5b896153407ad72327753222fdb3\",\"current\":\"\"},\"conf/security/policy/limited/default_local.policy\":{\"expected\":\"a0b98cbbb49184df973bb2c4a506e9bc6e025a696bc0c8054a6352cc3f9b4a38e3baf117c6834ddaddc38498556607ed4eda8f1bc683f662d61da50e0db0c8c2\",\"current\":\"\"},\"...\":\"Over 20 items, aborting normalization\"}}"
  },
  "id": "685c785297990"
}

**Comment by Adaniieel15** [comment]
Hey @yourITMatters ! I was looking into the “Invalid hash of binaries files” error you encountered in LibreSign, and I think it might be related to the version you have installed.

Do you know if you're using LibreSign version 11.2.4 or a more recent one? Version 11.2.3 introduced a fix that could address this exact issue with invalid hashes when some binary files are missing.

If you’ve just updated to the latest LibreSign version, try using the LibreSign graphical interface to regenerate the binaries (Java and JSignPdf). And if it fails again, it would be great if you could check the Nextcloud log and share the full error message that appears now. That way we can see if it’s still the same issue or if something changed.

Hope this helps you move forward with your case!

**Comment by yourITMatters** [comment]
> Hey [@yourITMatters](https://github.com/yourITMatters) ! I was looking into the “Invalid hash of binaries files” error you encountered in LibreSign, and I think it might be related to the version you have installed.
> 
> Do you know if you're using LibreSign version 11.2.4 or a more recent one? Version 11.2.3 introduced a fix that could address this exact issue with invalid hashes when some binary files are missing.
> 
> If you’ve just updated to the latest LibreSign version, try using the LibreSign graphical interface to regenerate the binaries (Java and JSignPdf). And if it fails again, it would be great if you could check the Nextcloud log and share the full error message that appears now. That way we can see if it’s still the same issue or if something changed.
> 
> Hope this helps you move forward with your case!

it's 11.2.4 after some digging today i did notice that i have two appdata folders.  i notice the log indicates the files are missing. is there a way to extract more data out of the log, such as what path is it searching to compare the file hash?

**Comment by Adaniieel15** [comment]
⚠️ Disclaimer  
I'm not officially part of the LibreSign support team, and honestly, sometimes I'm not entirely sure what I’m doing 😅 — I just try things that have worked for me in the past.

This procedure might have side effects or impact other parts of your installation, so please proceed at your own risk.

It worked for me in a Nextcloud AIO setup, but your mileage may vary. Hope this helps someone else move forward!

Let me know if it works for you!

---

## 🛠️ Fix LibreSign: "Invalid Hash of Binaries Files" (Nextcloud AIO)

### 💬 Implementer's Note

I ran into this error recently and after trying several things, the one that *seemed* to work was doing a **full reset** of the LibreSign binaries.

Some unexpected or leftover files (even if technically valid) were causing the hash check to fail. Here's what I did:

---

### 🧼 Clean Up Everything

Inside the Nextcloud container, I deleted all LibreSign binaries — valid or not — including old versions like `jsignpdf-2.2.2`.

```bash
docker exec -it nextcloud-aio-nextcloud bash
rm -rf /var/www/html/data/appdata_*/libresign/
```

---

### 🔄 Reinstall LibreSign Binaries

Once cleaned, I reinstalled everything:

```bash
cd /var/www/html
php occ libresign:install --all
```

---

### ✅ Verification

Then I went to:

**Settings > LibreSign > Check configuration**

The error `"Invalid hash of binaries files"` was gone and LibreSign started working as expected. 🎉

**Comment by yourITMatters** [comment]
@Adaniieel15  i actually tried something similar earlier, and i just tried your process as well. no success.  the only thing i can think that is unique to my deployment is that my data folders lives on a cifs share that is mounted to the data directory, but i don't believe this is a permissions issue as it was working and after the aio update it quit.

**Comment by vitormattos** [comment]
@yourITMatters every when is displayed the message "Invalid hash of binaries files", also is added a log entry with more details. Check the logs to identify what's happening.

**Comment by yourITMatters** [comment]
@vitormattos @Adaniieel15 the last response i posted was the extraction from the nextcloud.log file.  it appears to indicate that the binary files are missing.  the log shows the expected hash, followed by "current\":\"\" and one of the first lines says "file missing" .   it would appear that when libresign is installed from the appstore in NextcloudAIO it loads it's binaries to /mnt/ncdata/appdata_*AIOinstanceIDremovedFORsecurity*/libresign/, nevertheless i believe that libresign is anticipating the files being installed to /var/www/html/data/appdata_*/libresign/ .   Am i on the right track here?

** update **

On further testing i created a symlink inside the container from /mnt/ncdata/appdata_*AIOinstanceIDremovedFORsecurity*/  at /var/www/html/data/  which effectively gave me the path /var/www/html/data/appdata_*AIOinstanceIDremovedFORsecurity*/libresign

i tried to reinstall the binaries to no avail.  is there a separate log file for libresign?

**Comment by Fuseteam** [comment]
@yourITMatters try removing the jsign folder in /mnt/nc rather than in /var/www inside the nextcloud container, that's what worked for me: https://github.com/LibreSign/libresign/issues/4810#issuecomment-2996769529

**Comment by yourITMatters** [comment]
@Fuseteam I've tried that.  i actually went and removed the app with OCC then went to the data directory on the host and removed the whole libresign folder.  i then reinstalled the app.  it's the same result.  i believe the validation script may be looking in the wrong place for the binaries.  every other part of the app works until a signer goes in and signs a document. when they try to say the error "admin hasn't configured sign yet" is displayed. of course in the admin panel i am just stuck in the validation loop.

**Comment by Fuseteam** [comment]
> @Fuseteam I've tried that.  i actually went and removed the app with OCC then went to the data directory on the host and removed the whole libresign folder.  i then reinstalled the app.  it's the same result.  i believe the validation script may be looking in the wrong place for the binaries.  every other part of the app works until a signer goes in and signs a document. when they try to say the error "admin hasn't configured sign yet" is displayed. of course in the admin panel i am just stuck in the validation loop.

i didn't delete the whole app, only a subfolder.... not sure if there are some lingering files now i think you might want to run `find / -name libresign` and double check permissions of the involved directories with `ls -l`

**Comment by vitormattos** [comment]
> the last response i posted was the extraction from the nextcloud.log file.

@yourITMatters have two places that throws the message `Invalid hash of binaries files` and the reason of a place is added to log file:

https://github.com/LibreSign/libresign/blob/ee60795621b6ef148ca7403912bf09adba347980/lib/Service/Install/ConfigureCheckService.php#L345-L357

At both scenario, have different tips. If you didn't received a message about the debug mode, at the log entry will be added the entire result. Without the result that is added to nextcloud log, isn't possible identify what's happening.

You talked that deleted some files. Every when you delete a file at your OS, is important to index your files. Considering that the dependencies of LibreSign is added to appdata folder, I suggest to run `occ files:scan-app-data`.

> is there a separate log file for libresign?

No, LibreSign use the nextcloud.log file.

>  it would appear that when libresign is installed from the appstore in NextcloudAIO it loads it's binaries to /mnt/ncdata/appdata_AIOinstanceIDremovedFORsecurity/libresign/, nevertheless i believe that libresign is anticipating the files being installed to /var/www/html/data/appdata_*/libresign/ . Am i on the right track here?

LibreSign use the Nextcloud `iAppDataFactory` to identify where is the place of appdata folder. The appdata folder is added inside the `datadirectory` that come from config.php and if you didn't changed this system config setting, will be the folder `data` inside your Nextcloud root folder.

**Comment by vitormattos** [comment]
The installer refactor in #8456 has now been merged into `main`. That work explicitly used this report as regression/architecture input and changed download, checksum, target detection, appdata storage, and installer error handling. It does not prove this environment-specific report is resolved yet, so I am keeping the issue open. Once a release containing #8456 is available, please retest with that release; if the invalid-hash loop still reproduces, the new installer diagnostics should also give us a more precise failure point.
